### ISSUE TITLE
/conf and /keystroke directories aren't found under /opt/xwhep-server-11.0.0/ after intstallation

### ISSUE THREAD

**Issue by Zied-Guesmi** [lodygens/xtremweb-hep#33]
After I generated .deb files and installed the xwhep server on Linux ubuntu 16, according to the guide should have /conf and /keystroke directories in /opt/xwhep-server-11.0.0/ but I didn't find them. They exist in the client, the bridge, the worker and the client but not the server directory. How can I fix it ?

**Comment by lodygens** [comment]
As stated in the xwhep-admin-guide documentation (v 1.11.0), the server installation process is a two steps one:

"Since 8.3.1, the server installation package does not contain the server configuration. That last must be installed by its own installation package. The server installation package does not start services since configurations must be installed separately. Please see section 7.2."
