### ISSUE TITLE
How can I check if the worker is executing the job ?

### ISSUE THREAD

**Issue by Zied-Guesmi** [lodygens/xtremweb-hep#36]
I have installed the different parts of the middleware (the server on a VPS, a raspberry pi card as a worker and my computer is the client). I could upload data to the server and retrieve it successfully . But when I add an application and start a job the status is always 'pending'. I think the server is responsible for assigning tasks to the worker so I don't know what am I missing.
PS: I'm having warnings from the server that the socket is closed after the worker is registered.

![selection_011](https://user-images.githubusercontent.com/26070035/33246129-4cfd48e0-d311-11e7-9ca4-8092d3bddf9f.png)

**Comment by lodygens** [comment]
Hi Zied,
Concerning the warning on server log "socket is closed", this is nothing, don't worry.

Concerning your pending job, this is usually due to the fact that either you have no worker (which is not the case) or you have no worker correponding to the application requirement. For example, your worker has a ARM arch, running Linux and you registered your application with no binary for this architecture.

To check that, please execute the two following commands:
xwworkers --xwformat xml
xwapps --xwformat xml

And check this could propose a valid matchmaking.

Hope this help

**Comment by Zied-Guesmi** [comment]
Hi again,
Thank you, It totally makes sense. Now I'm getting the results of the execution. It was a question of  configuration matching (architecture). Thank so much !

**Comment by lodygens** [comment]
my pleasure 👍 
may I ask you what you do / intend to do with this middleware?

**Comment by Zied-Guesmi** [comment]
I'm working on the epm with Mr Heithem Abbess.

**Comment by lodygens** [comment]
great :D
